name: Hello

on: [push, pull_request]
jobs:
 test:
   name: javaprogram
   runs-on: self-hosted
   steps:
      - uses: actions/checkout@v3
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
           java-version: 1.11
      - name: setup java
        run: |
           javac trimukesh.java
           java trimukesh
